apiVersion: v1
kind: Service
metadata:
  labels:
    app: site-generator
  name: site-generator
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: site-generator
#  type: LoadBalancer

